baseURL: https://www.kreedzt.com/
languageCode: "en-us"
title: "Kreedzt's Index Page"
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-VCP5R6F7JW

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Kreedzt's Index Page"
    description: "Kreedzt's blog"
    keywords: ["Index", "Kreedzt", "PaperMod"]
    author: "Kreedzt"
    DateFormat: "2006-01-02"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    
    profileMode:
        enabled: true
        #title: "<Title>" # optional default will be site title
        subtitle: "Kreedzt's Index Page"
        #imageUrl: "<image link>" # optional
        #imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Blog
              url: "https://blog.kreedzt.com/"
            - name: Github
              url: "https://github.com/Kreedzt"

    #socialIcons: # optional
    #    - name: "<platform>"
    #        url: "<link>"
    #    - name: "<platform 2>"
    #        url: "<link2>"